### ISSUE TITLE
Request for file size reduction in .dmg file for MacOS under version releases

### ISSUE THREAD

**Issue by waridrox** [moja-global/FLINT-JSON-Interface#29]
**Is your feature request related to a problem? Please describe.**
Currently the `.dmg` file for MacOS systems is very large (about 868 MB) in comparison to other file formats.

**Describe the solution you'd like**
The `.dmg` file size should be reduced to a bare minimum. 

**Describe alternatives you've considered**
I have created a `.dmg` image whose overall size is reduced to 98.8 MB which was 868 MB before. No functionality is lost. Have a look => https://drive.google.com/file/d/14_N1UqFZdrWfF9FJJTJSdIW3ci6RCxqx/view?usp=sharing

**Testing environment**
Tested on MacOS 11.0.1 
@abhi211199

**Comment by abhi211199** [comment]
Hey @waridrox, thanks for your contribution to the project! For the timing, you can add an entry of the reduced file version in the README, and once, new features are implemented in the project, we can create a new Release with the updated dmg file!
