### ISSUE TITLE
Adding Contributors

### ISSUE THREAD

**Issue by abhi211199** [moja-global/FLINT-JSON-Interface#3]
@all-contributors please add @abhi211199 for code

**Comment by gmajan** [comment]
@all-contributors please add @abhi211199 for code

**Comment by abhi211199** [comment]
@gmajan sir, I couldn't understand why the bot didn't respond in first place. Is it something like only members of the organisation can use the all-contributors bot?

**Comment by gmajan** [comment]
Hi Abhishek
Well done. Only, the All-Contributors only works in a comment (as I have done) not in a primary issue. The reasoning is that you can only gain your recognition in response to work achieved. But I think you have really deserved it. So congrats. You are on your own landing page.

Feel free to claim your recognition in all other repos where you have made contributions. And keep up the good work!

**Comment by abhi211199** [comment]
Oh, now I understand the complete thing about all-contributors bot. Thanks for explaining. 
I will add you and @mfellows sir as reviewers.

**Comment by abhi211199** [comment]
@all-contributors please add @gmajan for review

@all-contributors please add @mfellows for review

**Comment by abhi211199** [comment]
@all-contributors please add @gmajan for review

**Comment by abhi211199** [comment]
@all-contributors please add @mfellows for review

**Comment by abhi211199** [comment]
@all-contributors please add @mfellows for review

**Comment by gmajan** [comment]
Well done.

**Comment by gmajan** [comment]
I saw that you copied some of the code in the md file. That is another way to get the contributors into the list. It is just a bit more hassle.

**Comment by abhi211199** [comment]
Yeah 😅, I messed up while resolving merge conflict for a PR and mis-formatted a bit of code in README.md, and had to copy the code from previous commit to resolve it.
